# configuration files that tells greenhouseFiller.py where to look for files, ect
---
person:
  first_name: "Eric"
  last_name: "Son"
  email: "nuxeric@hotmail.com"
  phone: "778-707-3742"
  resume:
    path: TestWordDocument.docx
  cover_letter:
    path: TestWordDocument.docx
  education:
    school: "University of British Columbia"
    degree: "Bachelor's Degree"
    discipline: "Computer Science"
    start date:
      month: "09"
      year: "2017"
    end date:
      month: "04"
      year: "2022"
  transcript: TestWordDocument.docx
  linkedin profile: "https://www.linkedin.com/in/eric-sonn/"
  website: "http://ericsonn.com/"
