# configuration files that tells greenhouseFiller.py where to look for files, ect
---
person:
  first_name: "Eric"
  last_name: "Son"
  email: "nuxeric@hotmail.com"
  phone: "778-707-3742"
  resume:
    path: TestWordDocument.docx
  cover_letter:
    path: TestWordDocument.docx
  education:
    school_name: The University of British Columbia
    degree: Bachelor's Degree
    discipline: Computer Science
    start_date:
    end_date:
  transcript: TestWordDocument.docx
  linkedIn: "https://www.linkedin.com/in/eric-sonn/"
  website: "http://ericsonn.com/"
